name: release_pypi

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_PYTHON_VERSION: 3.8
  BUILD_POETRY_VERSION: 1.1.13
  PACKAGE_NAME: enex2notion

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Install Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.BUILD_POETRY_VERSION }}

      - name: Build project for distribution
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish

  publish_tap:
    needs: [publish_pypi]
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.BREW_BUMP_TOKEN }}
          tap: vzhd1701/tap
          formula: ${{ env.PACKAGE_NAME }}
